import os,asyncio
from sarvamai import SarvamAI,AsyncSarvamAI
from dotenv import load_dotenv
from planner import PlannerAgent
from writer import Writer
from fact_checker import FactChecker
load_dotenv()
api_key = os.getenv("SARVAM_API_KEY")

FOOTER = """
---
This report was generated by an AI language model and may contain factual
errors or mixed-up details. It is a draft for review, not a verified
historical record. It is not intended to rank, favor, or offend any
community."""

planner_model = "sarvam-105b"
planner_prompt = """You are a research planner for community history reports.
Given a community name, output an outline as JSON only. No prose, no fences.
Schema: {"title": str, "sections": [{"id": "1", "title": str, "subsections":
[{"id": "1.1", "title": str, "goal": str, "period": str, "source_types": [str]}]}]}

Rules:
- Sections are ERAS, ordered earliest to latest: earliest references and origin
  traditions, ancient, early medieval, medieval, colonial, post-independence.
- Give most weight to the earliest periods. Modern (20th century+) origin theories
  get one subsection at most, labelled modern_scholarship or oral_tradition.
- source_types: allowed values are inscription, literary_text, colonial_record,
  oral_tradition, modern_scholarship. Choose the evidence a historian would
  actually look for in that period (inscriptions, copper plates, medieval
  literature, colonial gazetteers and ethnographies).
- If no written evidence is known for a period, still include it, use
  ["oral_tradition"], and say so in the goal.
- 4-5 sections, 2-3 subsections each. Contested claims must be flagged in the goal.
- Every goal must ask for a neutral, academic account — not a celebratory or
  promotional one.
- Never frame a section around the community being superior, special, or more
  important than others. Do not plan sections comparing it against other groups.
- Any subsection about leadership, rank, or notable people must focus on specific
  named individuals and their documented actions, not on claiming a trait for
  the whole community.
- Any subsection about caste status or disputed origins must say, in the goal,
  that it should be written as a claim from a source, not as settled fact.
- Any subsection about modern caste politics (classification, reservation, etc.)
  must say, in the goal, to cover different viewpoints fairly."""

writer_model = "sarvam-105b"
writer_retry_token_schedule = [3000, 5000, 8000]
writer_prompt = """You are a history section writer. You will be given a section
title, a goal, a historical period, and allowed source types.
Rules:
- Write ~200-300 words covering ONLY that period. Do not drift into other eras.
- Use ONLY the given source_types as your evidence basis. If source_types is
  ["oral_tradition"], say so explicitly — do not invent inscriptions or texts.
- Separate established fact from tradition/theory using phrasing like
  "According to X" or "Oral tradition holds that Y", never state theories as fact.
- Cite claims inline as [1], [2], matching a "Sources:" list at the end
  describing what each source is (e.g. "[1] Colonial-era gazetteer record").
- If evidence for this period is genuinely thin, say so rather than padding.
- Write in a plain, neutral, encyclopedia-style tone. Do not use celebratory,
  promotional, or glorifying language.
- Never say or imply this community is superior, nobler, or more important than
  any other community. Do not compare or rank it against other groups.
- Describe leadership, bravery, or skill as things specific named individuals did,
  not as a trait the whole community has. Do not generalize one person's actions
  to "the community's nature."
- If the section involves caste rank, social status, or disputed origin claims,
  present them as claims made by the community or by specific sources — never
  state them as settled fact.
- If the section touches modern political topics (such as caste classification
  or reservation policy), describe different viewpoints fairly without taking
  a side."""

fact_checker_model = "sarvam-105b"
fact_checker_prompt = """You are checking and correcting a full history report made of multiple sections.
You will get the community this report should be about, reference material found online,
and the full report broken into sections, each marked with its id and title.

For each section, check:
1. Does it describe a DIFFERENT community as if it were this one?
2. Does anything in it contradict the reference material?
3. Does it state anything as plain fact that should say "oral tradition says"
or "according to X" instead?

Fix any problems directly in the text. If a section is fine, return it unchanged.
You must return EVERY section you were given, in the same order, with the same ids.

Reply with JSON only, no other text, in this exact shape:
{"sections": [{"id": "...", "title": "...", "content": "corrected or unchanged text"}]}"""


client = SarvamAI(api_subscription_key = api_key)
async_client = AsyncSarvamAI(api_subscription_key = api_key)

plan = PlannerAgent(
    client = client ,
    planner_model = planner_model ,
    planner_prompt = planner_prompt
)
writer = Writer(
    client = async_client ,
    writer_model = writer_model ,
    writer_retry_token_schedule = writer_retry_token_schedule ,
    writer_prompt = writer_prompt
)

fact_checker = FactChecker(
    client = client ,
    fact_checker_model = fact_checker_model ,
    fact_checker_prompt = fact_checker_prompt
)

community = "Padma Velama"

planned_outline_json = plan.planner(community=community)
raw_result = asyncio.run(writer.write_all_sections(planned_outline_json.model_dump() ,community=community))
result = fact_checker.fact_check_all(raw_result ,community=community)

for r in result:
    print(f"\n-> {r.title}\n\t{r.content}\n")
print(FOOTER)